version: '3'
services:
  postgres-number-inventory:
    image: postgres:12-alpine
    container_name: postgres-number-inventory
    volumes:
      - ./script/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - 5432:5432
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '1.25GB'
  
  redis-number-inventory:
    image: redis:6.2.0-alpine
    container_name: redis-number-inventory
    ports:
      - 6379:6379