version: '3'
services:
  postgres-number-inventory:
    image: mysql:8
    container_name: mysql-number-inventory
    environment:
      MYSQL_DATABASE: 'number_inventory'
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      - 3306:3306
    restart: unless-stopped