spring:
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/number_inventory}
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true